# mysql
# https://github.com/ccommit-dev/Board-Server/tree/main
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mariadb://localhost:3306/BOARD_SERVER
spring.datasource.username=root
spring.datasource.password=siwan1993@
mybatis.mapper-locations=classpath:com.fastcampus.boardserver.mapper/*.xml